# kata-containers/tools/packaging/kata-deploy/kata-rbac/base/kata-rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kata-deploy-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kata-deploy-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: ["node.k8s.io"]
    resources: ["runtimeclasses"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kata-deploy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kata-deploy-role
subjects:
  - kind: ServiceAccount
    name: kata-deploy-sa
    namespace: kube-system
# kata-containers/tools/packaging/kata-deploy/kata-deploy/base
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kata-deploy
  template:
    metadata:
      labels:
        name: kata-deploy
    spec:
      serviceAccountName: kata-deploy-sa
      hostPID: true
      containers:
      - name: kube-kata
        image: quay.io/kata-containers/kata-deploy:3.10.0
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "/opt/kata-artifacts/scripts/kata-deploy.sh cleanup"]
        command: ["bash", "-c", "/opt/kata-artifacts/scripts/kata-deploy.sh install"]
        # NOTE: Please don't change the order of the environment variables below.
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEBUG
          value: "false"
        - name: SHIMS
          value: "clh cloud-hypervisor dragonball fc qemu qemu-coco-dev qemu-runtime-rs qemu-sev qemu-snp qemu-tdx stratovirt qemu-nvidia-gpu qemu-nvidia-gpu-snp qemu-nvidia-gpu-tdx"
        - name: DEFAULT_SHIM
          value: "qemu"
        - name: CREATE_RUNTIMECLASSES
          value: "false"
        - name: CREATE_DEFAULT_RUNTIMECLASS
          value: "false"
        - name: ALLOWED_HYPERVISOR_ANNOTATIONS
          value: ""
        - name: SNAPSHOTTER_HANDLER_MAPPING
          value: ""
        - name: AGENT_HTTPS_PROXY
          value: ""
        - name: AGENT_NO_PROXY
          value: ""
        - name: PULL_TYPE_MAPPING
          value: ""
        - name: INSTALLATION_PREFIX
          value: ""
        securityContext:
          privileged: true
        volumeMounts:
        - name: crio-conf
          mountPath: /etc/crio/
        - name: containerd-conf
          mountPath: /etc/containerd/
        - name: host
          mountPath: /host/
      volumes:
      - name: crio-conf
        hostPath:
          path: /etc/crio/
      - name: containerd-conf
        hostPath:
          path: /etc/containerd/
      - name: host
        hostPath:
          path: /
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

# kata-containers/tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-clh
handler: kata-clh
overhead:
  podFixed:
    memory: "130Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-cloud-hypervisor
handler: kata-cloud-hypervisor
overhead:
  podFixed:
    memory: "130Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-dragonball
handler: kata-dragonball
overhead:
  podFixed:
    memory: "130Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-fc
handler: kata-fc
overhead:
  podFixed:
    memory: "130Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-qemu-nvidia-gpu
handler: kata-qemu-nvidia-gpu
overhead:
  podFixed:
    memory: "160Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-qemu-se
handler: kata-qemu-se
overhead:
  podFixed:
    memory: "2048Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-qemu-sev
handler: kata-qemu-sev
overhead:
  podFixed:
    memory: "2048Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-qemu-snp
handler: kata-qemu-snp
overhead:
  podFixed:
    memory: "2048Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-qemu-tdx
handler: kata-qemu-tdx
overhead:
  podFixed:
    memory: "2048Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-qemu
handler: kata-qemu
overhead:
  podFixed:
    memory: "160Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-remote
handler: kata-remote
overhead:
  podFixed:
    memory: "120Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-stratovirt
handler: kata-stratovirt
overhead:
  podFixed:
    memory: "130Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
# kata-containers/tools/packaging/kata-deploy/examples/test-deploy-kata-clh.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: php-apache-kata-clh
  name: php-apache-kata-clh
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache-kata-clh
  template:
    metadata:
      labels:
        run: php-apache-kata-clh
    spec:
      runtimeClassName: kata-clh
      containers:
        - image: registry.kubeblocks.cloud/apecloud/hpa-example:latest
          imagePullPolicy: Always
          name: php-apache
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 200m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-kata-clh
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: php-apache-kata-clh
  sessionAffinity: None
  type: ClusterIP