name: Cherry Pick
on:
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  cherry-pick:
    name: Cherry Pick
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/cherry-pick')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Automatic Cherry Pick
        uses: apecloud-inc/gha-cherry-pick@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

  send-message:
    permissions:
      id-token: write
      contents: read
    needs: [ cherry-pick ]
    if: ${{ failure() || cancelled() }}
    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.6.0
    with:
      TYPE: "5"
      BOT_TYPE: "specify"
      BOT_WEBHOOK: "${{ vars.CHERRY_PICK_BOT_WEBHOOK }}"
      CONTENT: " ${{ github.event.comment.body }} error"
      PR_NUMBER: "${{ github.event.issue.number }}"
    secrets: inherit

  label-pick:
    name: Label Pick
    if: ${{ github.event.issue.pull_request != '' && (contains(github.event.comment.body, '/pick') || contains(github.event.comment.body, '/nopick')) }}
    uses: apecloud-inc/apecloud-cd/.github/workflows/pull-request-label-pick.yml@v0.6.0
    secrets: inherit
