name: Manifests Charts Images Check

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'The version of release'
        type: string
        required: true
        default: ''
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: 'The version of release'
        type: string
        required: true
        default: ''


run-name: check charts images ${{ inputs.RELEASE_VERSION }}

env:
  CR_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  HELM_VERSION: v3.15.4
  CHART_PROJECT_ID: ${{ secrets.JIHULAB_PROJECT_ID }}
  CHART_ACCESS_USER: ${{ secrets.JIHULAB_ACCESS_USER }}
  CHART_ACCESS_TOKEN: ${{ secrets.JIHULAB_ACCESS_TOKEN }}
  MANIFESTS_FILE: "apecloud/manifests/deploy-manifests.yaml"

jobs:
  images-check:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get-version.outputs.release-version }}
    steps:
      - name: get version
        id: get-version
        run: |
          RELEASE_VERSION="${{ inputs.RELEASE_VERSION }}"
          if [[ "${RELEASE_VERSION}" != "v"* ]]; then
              RELEASE_VERSION="v${RELEASE_VERSION}"
          fi
          echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Checkout apecloud Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud
          path: apecloud
          token: ${{ env.CR_TOKEN }}
          ref: "release-0.27"
          # ref: ${{ steps.get-version.outputs.release-version }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: manifests images check
        run: |
          MANIFESTS_FILE="${{ env.MANIFESTS_FILE }}"
          bash .github/scripts/manifests_charts_image_check.sh "${MANIFESTS_FILE}"
