name: Pull Request Label Check

on:
  pull_request:
    types: [ labeled, unlabeled, synchronize ]
    branches:
      - main
      - release-*

jobs:
  pr-label-check:
    name: check-pr-label
    uses: apecloud-inc/apecloud-cd/.github/workflows/pull-request-label-check.yml@v0.6.0
    with:
      CHECK_LABEL: "pick"
    secrets: inherit

      
