name: Save K8s Images

on:
  workflow_dispatch:
    inputs:
      K8S_VERSION:
        description: 'kubernetes-airgap version'
        required: true
        default: 'v1.33.3'
        type: choice
        options:
          - v1.27.7
          - v1.30.13
          - v1.32.5
          - v1.33.3
      SEALOS_VERSION:
        description: 'sealos version'
        required: false
        default: 'v5.1.0-rc3'
      HELM_VERSION:
        description: 'helm version'
        required: false
        default: 'v3.18.4'
      METRICS_SERVER_VERSION:
        description: 'metrics-server version'
        required: false
        default: 'v0.7.1'
      CALICO_VERSION:
        description: 'calico-airgap version'
        required: false
        default: 'v3.28.0'
      COREDNS_VERSION:
        description: 'coredns version'
        required: false
        default: 'v0.0.1'
      OPENEBS_VERSION:
        description: 'openebs version'
        required: false
        default: 'v3.10.0'


run-name: save K8s:${{ inputs.K8S_VERSION }} sealos:${{ inputs.SEALOS_VERSION }}

env:
  K8S_NAME: "apecloud-kube-airgap"
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
  OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
  OSS_ENDPOINT: "oss-cn-zhangjiakou.aliyuncs.com"
  OSS_BUCKET: "kubeblocks-oss"

jobs:
  save-k8s-images:
    name: save k8s images
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: save k8s images
        env:
          k8s_name: ${{ env.K8S_NAME }}
          k8s_version: ${{ inputs.K8S_VERSION }}
          sealos_version: ${{ inputs.SEALOS_VERSION }}
          helm_version: ${{ inputs.HELM_VERSION }}
          metrics_server_version: ${{ inputs.METRICS_SERVER_VERSION }}
          calico_version: ${{ inputs.CALICO_VERSION }}
          coredns_version: ${{ inputs.COREDNS_VERSION }}
          openebs_version: ${{ inputs.OPENEBS_VERSION }}
        run: |
          bash .github/scripts/save_k8s_images.sh

      - name: get artifact size
        run: |
          sealos images
          du -sh ${{ env.K8S_NAME }}-${{ inputs.K8S_VERSION }}.tar.gz

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          access-key-id: "${{ env.OSS_KEY_ID }}"
          access-key-secret: "${{ env.OSS_KEY_SECRET }}"
          endpoint: "${{ env.OSS_ENDPOINT }}"

      - name: Upload artifact to oss
        id: upload_to_oss
        run: |
          IMAGE_PKG_NAME="${{ env.K8S_NAME }}-${{ inputs.K8S_VERSION }}.tar.gz"
          ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/artifact/${IMAGE_PKG_NAME}
          upload_ret=$?
          if [[ $upload_ret -eq 0 ]]; then
              echo "upload ${IMAGE_PKG_NAME} to oss successfully"
          else
              exit 1
          fi
          
          IMAGE_PKG_NAME_MD="${IMAGE_PKG_NAME}.md5"
          echo "upload ${IMAGE_PKG_NAME_MD} to oss ..."
          upload_ret=0
          for i in {1..10}; do
              md5sum ${IMAGE_PKG_NAME} > ${IMAGE_PKG_NAME_MD}
              md5sum_check=$(md5sum -c ${IMAGE_PKG_NAME_MD})
              check_ret=$?
              if [[ $check_ret -eq 0 && "${md5sum_check}" == *"OK" ]]; then
                  echo "${md5sum_check}"
              else
                  sleep 1
                  continue
              fi
          
              echo "ossutil cp ${IMAGE_PKG_NAME_MD} to oss://${{ env.OSS_BUCKET }}/artifact/${IMAGE_PKG_NAME_MD} ..."
              ossutil cp -rf ./${IMAGE_PKG_NAME_MD} oss://${{ env.OSS_BUCKET }}/artifact/${IMAGE_PKG_NAME_MD}
              upload_ret=$?
             
              if [[ $upload_ret -eq 0 ]]; then
                  break
              fi
              sleep 1
          done
          
          if [[ $upload_ret -eq 0 ]]; then
              echo "upload ${IMAGE_PKG_NAME_MD} to oss successfully"
          fi

  save-result:
    runs-on: ubuntu-latest
    needs: [ save-k8s-images ]
    if: ${{ always() }}
    outputs:
      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
      save-result: ${{ steps.get_save_result.outputs.save_result }}
    steps:
      - name: get save result
        id: get_save_result
        run: |
          SAVE_RESULT="error"
          IMAGE_PKG_NAME="${{ env.K8S_NAME }}-${{ inputs.K8S_VERSION }}.tar.gz"
          if [[ "${{ needs.save-k8s-images.result }}" == "success" ]]; then
              SAVE_RESULT="success"
              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/artifact/${IMAGE_PKG_NAME}"
          fi
          echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
          echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT

#  send-message:
#    permissions:
#      id-token: write
#      contents: read
#    needs: [ save-result ]
#    if: ${{ always() }}
#    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
#    with:
#      TYPE: "2"
#      CONTENT: "save k8s image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
#    secrets: inherit
