name: Save Manifests Images

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'The version of release'
        type: string
        required: true
        default: ''
      ENABLE_ADDONS:
        description: 'Enable save addon images (e.g. apecloud-mysql|clickhouse|elasticsearch|kafka|mongodb|mysql|oceanbase|postgresql|qdrant|rabbitmq|redis|starrocks|zookeeper|damengdb|kingbase)'
        type: string
        required: false
        default: 'false'
      SELF_RUNNER:
        description: "Enable self runner"
        default: 'false'
        type: choice
        required: false
        options:
          - false
          - true

run-name: save images ${{ inputs.RELEASE_VERSION }} ${{ inputs.ENABLE_ADDONS }}

permissions:
  id-token: write
  contents: read

jobs:
  check-manifests-image:
    uses: ./.github/workflows/manifests-image-check.yml
    with:
      RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
    secrets: inherit

  check-manifests-charts-image:
    uses: ./.github/workflows/manifests-charts-image-check.yml
    with:
      RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
    secrets: inherit

  save-cloud-images:
    needs: [ check-manifests-image, check-manifests-charts-image ]
    uses: ./.github/workflows/manifests-images-save.yml
    with:
      RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
      IS_ADDON: "false"
    secrets: inherit

  check-self-runner:
    needs: [ check-manifests-image, check-manifests-charts-image ]
    if: ${{ inputs.ENABLE_ADDONS != 'false' && inputs.ENABLE_ADDONS != '' }}
    runs-on: ubuntu-latest
    outputs:
      self-runner: ${{ steps.check-self-runner.outputs.self-runner }}
      enable-addons: ${{ steps.check-self-runner.outputs.enable-addons }}
    steps:
      - name: check self runner
        id: check-self-runner
        run: |
          SELF_RUNNER="${{ inputs.SELF_RUNNER }}"
          ENABLE_ADDONS="${{ inputs.ENABLE_ADDONS }}"
          if [[ "${ENABLE_ADDONS}" == "true" ]]; then
              SELF_RUNNER="true"
              ENABLE_ADDONS=""
          else
              ADDON_COUNTS=$(echo "${{ inputs.ENABLE_ADDONS }}" | grep -o "|" | wc -l)
              if [[ ${ADDON_COUNTS} -gt 8 ]]; then
                  SELF_RUNNER="true"
              fi
          fi
          echo "self-runner=${SELF_RUNNER}" >> $GITHUB_OUTPUT
          echo "enable-addons=${ENABLE_ADDONS}" >> $GITHUB_OUTPUT

  save-addon-images:
    needs: [ check-self-runner ]
    if: ${{ inputs.ENABLE_ADDONS != 'false' && inputs.ENABLE_ADDONS != '' && needs.check-self-runner.outputs.self-runner != 'true' }}
    uses: ./.github/workflows/manifests-images-save.yml
    with:
      RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
      IS_ADDON: "true"
      ENABLE_ADDONS: "${{ needs.check-self-runner.outputs.enable-addons }}"
    secrets: inherit

  save-addon-images-self:
    needs: [ check-self-runner ]
    if: ${{ inputs.ENABLE_ADDONS != 'false' && inputs.ENABLE_ADDONS != '' && needs.check-self-runner.outputs.self-runner == 'true' }}
    uses: ./.github/workflows/manifests-images-save-self.yml
    with:
      RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
      IS_ADDON: "true"
      ENABLE_ADDONS: "${{ needs.check-self-runner.outputs.enable-addons }}"
    secrets: inherit

  send-message:
    permissions:
      id-token: write
      contents: read
    needs: [ check-manifests-image, check-manifests-charts-image ]
    if: ${{ failure() || cancelled() }}
    uses: apecloud-inc/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.0
    with:
      TYPE: "2"
      BOT_TYPE: "package"
      CONTENT: "save images ${{ inputs.RELEASE_VERSION }} error"
    secrets: inherit
